### PR TITLE
Fix/translation functions fixes (#8)

### PR DESCRIPTION
**Pull request by bmihelac**

### CODE REVIEW

**Review by ezrajrice — DISMISSED** [review]

**Comment by bmihelac** [comment]
I see - checks are failing with "E501 line too long (116 > 100 characters)", ie:

https://github.com/ezrajrice/django_advanced_password_validation/actions/runs/5528529600/jobs/10095161044#step:6:20

I have reformatted source files with black lets see result of checks now

**Comment by ezrajrice** [comment]
The tests are now passing. It looks like there might be something wrong with the Lint action using Black. I need to go in and check it. I don't think you need to do anything else on your end. Thanks for the PR!

**Comment by ezrajrice** [comment]
Black started failing within GH Actions. Since the code was formatted with Black locally before pushing, I'm okay with merging this now.

**Comment by bmihelac** [comment]
@ezrajrice thanks for quick action and merging

**Pull request merged**
