### PR TITLE
Add tests, CI and other things

### PR DESCRIPTION
**Pull request by mostafa**
Hey @ezrajrice,

I this PR, I added these things:
1. Tests
2. Function docstrings
3. Fix bugs and slightly refactored parts of the code
4. Linters (mypy, flake8 and interrogate)
5. CI using GitHub Actions and its [results](https://github.com/mostafa/django-advanced-password-validation/actions/runs/3381540527)
6. Coverage using [coveralls](https://coveralls.io/github/mostafa/django-advanced-password-validation)

I'd be happy to have your review, and possible merge of the  PR. I can also add a separate deployment workflow if that's manual for now. I have a few other suggestions if you want to hear. Make sure to open an account with your GitHub credentials on https://coveralls.io/, and add the repository, so you can see the coverage on your own account.

### CODE REVIEW

**Review by ezrajrice — APPROVED** [review]
This all looks great! I appreciate you helping to make this project better.

**Comment by mostafa** [comment]
@ezrajrice I am not sure about your deployment process, which is why I haven't changed versions and haven't added any release process to the GH Actions.

**Comment by ezrajrice** [comment]
> @ezrajrice I am not sure about your deployment (release) process, which is why I haven't changed versions and haven't added any release process to the GH Actions.

The deployment process is currently manual. I'm working on automating it. I'm going to be changing the repo slightly so that tagged versions are created and automatically released to pypi and test.pypi

**Comment by mostafa** [comment]
@ezrajrice See if this helps:
https://github.com/grafana/django-saml2-auth/blob/main/.github/workflows/deploy.yml

**Pull request merged**
